apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: calc-it-up-ingress
  labels:
    app.kubernetes.io/name: calc-it-up-ingress
spec:
  rules:
  - host: calculator.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: calculator-service
            port:
              number: 30007
